### ISSUE TITLE
Create reliable way to build/deploy cordova app

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina#180]
I wondered about a script that would install any dependencies, etc. and build a cordova app so that anyone can easily build and deploy the app to their iphone or create a runnable app for android.

Maybe putting some of this in the .gitignore will make it feasible to store the codova directory in git?

```
# cordova
cordova/node_modules
cordova/plugins
cordova/platforms
cordova/res
```

Related to #69

**Comment by Jbcampbe** [comment]
I'm afraid doing automatic ios/android build from CI will not be feasible. The native project require some custom configuration and cordova-cli is just not trustworthy
