### ISSUE TITLE
Improve transfer "selected tools" flow

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina#284]
Suppose I want to transfer a makita drill and a dewalt sawzall. I begin a transfer session, search for "makita" and find the drill (tool 1,013), and select the checkmark. Then I clear the search; the tool shoots down to the bottom of the list (because of its high retina ID) or it possibly dissapears all together, if we ever implement paging.

A similar thing would happen when you scan a tool. The tool will get a checkmark, but that tool may or may not be on the screen.

I'm thinking we need *some* way of having a "list" of selected tools so that a user can have confidence that the tool they selected or scanned is actually in the "cart"

**Comment by Jbcampbe** [comment]
Isn't that what `show selected` is for?

**Comment by ekraihan** [comment]
Yea, I suppose...
