### ISSUE TITLE
Wrong month in date span on tool history

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina#341]
On the tool history page, when I select a date span in the month of may, the dates are displayed as the month of April:

![image](https://user-images.githubusercontent.com/17623856/58529710-f1575780-81a9-11e9-89c0-36da74de9218.png)

**Comment by amenders** [comment]
I’ve seen this come up before; the dates are 0-based, meaning that days in January show up as month 0.

-Amos Endersen
