### ISSUE TITLE
Release/3.2.0 Bug Hunt

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina#345]
### Bugs

- [x] User not successfully logging out (when you login as a different user, you appear to still be logged in as the previous user)

- [x] Clicking phone call/email buttons on a tool throws error:
![image](https://user-images.githubusercontent.com/17623856/60852420-aaf01200-a1c5-11e9-9be8-4a59596993bd.png)

- [x]  When I go to view a tool with an empty purchased-from field, the same error as this ^ is thrown

- [x] Sometimes a tool history entry is not showing an arrow between two statuses (when the status changes). Could the arrow also not be showing for other fields as well?

- [x] Tool history entry shows PHOTO UPDATED even when the photo was not updated

- [x] During a transfer, clicking a checkbox both adds the tool to the transfer list, and shows me tool details. I'm thinking we don't want to see the tool detail every time we select a checkbox.

- [x] When adding a tool and leaving the model year blank, it the value sent for the year is the empty string. The api then replies with a 400 that "year" should be an "Int." This results in the tool failing to save.

- [x] For the date picker in both the add and edit tool flow, when I try to get the picker to go away by clicking on the date button again (i.e. clicking here: <img width="528" alt="Screen Shot 2019-07-11 at 11 49 13 PM" src="https://user-images.githubusercontent.com/17623856/61101094-94042680-a436-11e9-9606-580ce4dc2a28.png">),
 I get this error:
![image](https://user-images.githubusercontent.com/17623856/61101047-60290100-a436-11e9-9096-27a0b9d044de.png)

- [x] When editing the price for a tool, typing any number in [1-5] does not change the price, typing any number in [6-9] increments the price, and typing 0 *twice* adds a 0

### Notes/Questions
- [x] Small detail, but possibly make the font here (during a transfer) smaller for desktop? Or make the dropdown wider?
![image](https://user-images.githubusercontent.com/17623856/60852629-792b7b00-a1c6-11e9-845a-90f7a7ff9d26.png)

- [x] When I go to decommission a tool, but then press Cancel (or just click away from the popup), the tool stays commissioned but I get a swal saying "Success." I'm guessing we don't want "Success" on "Cancel".

- [x] Do we want to show the decommission reason on the tool history page under entries that have a tool action of "DECOMMISSION"?

- [x] I noticed that with the current logic, an admin can only transfer tools that either he or the Shop owns. Is that correct logic?

- [x] ~~I don't have any awesome solutions to this, and it may not be a big deal... when we delete a user, any tools assigned to that user stay assigned to that user. On the tool search page, you can see the deleted user's name associated to a tool, but when you go to search for tools owned by that user, the user does not appear in the dropdown. This is just a little bit of an odd experience, because what if an admin wants to transfer all tools belonging to that user to another user; they can't do an exclusive search on that user's name. (Note: if you just to a fuzzy search for the user, the search will work, but it is possible that tools belonging to other users will come back in the search if their name is close enough to the deleted user's name)~~ moved to separate ticket

**Comment by Jbcampbe** [comment]
@ekraihan are you ok with tackling that last item in a different release (if at all)?

**Comment by ekraihan** [comment]
> @ekraihan are you ok with tackling that last item in a different release (if at all)?

Yes, very fine
